
Neos:
  Demo:
    flickr:
      tagStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&tags=%s'
      userStreamUriPattern: 'http://api.flickr.com/services/feeds/photos_public.gne?format=json&nojsoncallback=1&id=%s'
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          fusionRenderingPath: print
          title: 'Neos.Demo:Main:editPreviewModes.print'
          position: 200
      translation:
        autoInclude:
          Neos.Demo:
            - Main
            - 'NodeTypes/*'
    sites:
      '*':
        contentDimensions:
          # the defaultDimensionSpacePoint is used when resolving the "/" URL.
          defaultDimensionSpacePoint:
            language: en_US

  ContentRepositoryRegistry:
    contentRepositories:
      default:
        contentDimensions:
          language:
            label: 'Neos.Demo:Main:contentDimensions.language'
            icon: icon-language
            values:
              'en_US':
                label: English (US)
                # TODO -> site config uriSegment: en
                specializations:
                  'en_UK':
                    label: English (UK)
                    # TODO -> site config uriSegment: uk

              'de':
                label: German
                specializations:
                  nl:
                    label: Dutch
                    # TODO -> site config uriSegment: nl
              'fr':
                label: French
                # TODO -> site config uriSegment: fr
              'da':
                label: Danish
                # TODO -> site config uriSegment: da
              'lv':
                label: Latvian
                # TODO -> site config uriSegment: lv

