Neos:
  Demo:
    debugMode: false
  Neos:
    userInterface:
      translation:
        autoInclude:
          Neos.Demo:
            - Main
            - 'NodeTypes/*'

      navigateComponent:
        nodeTree:
          loadingDepth: 2
        structureTree:
          loadingDepth: 3

    nodeTypes:
      groups:
        forms:
          position: end
          label: 'Neos.Demo:Main:nodeTypes.groups.forms'
          collapsed: false

    Ui:
      resources:
        javascript:
          'Neos.Demo:CKEConfig':
            #TODO Rename this
            resource: resource://Neos.Demo/Public/Scripts/CKEConfig/Plugin.js
